/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ventas;

import javax.swing.*;
import java.lang.*;
import java.sql.*;
import java.util.Date;

/**
 *
 * @author Freddy
 */
public class Articulos extends javax.swing.JFrame {

    /**
     * Creates new form Articulos
     */
   
    public static Date FechaActual;
    public Articulos() {
        
        initComponents();
        FechaActual = new Date(); 
        Integer Dia1 = FechaActual.getDate();
        Integer Mes1 = FechaActual.getMonth()+1;
        Integer Ano1 = FechaActual.getYear()-100;
        String Dia = Dia1.toString();
        String Mes = Mes1.toString();
        String Ano = Ano1.toString();
        
        String Fecha;
        
        jTextIdArticulo.setText(String.valueOf(Jbbc.Valor_Maximo("IdArticulo", "Articulo")));
      
        if(Dia1<10) Dia = "0"+Dia;
        if(Mes1<10) Mes = "0"+Mes;
        if(Ano1<10) Ano = "0"+Ano;
        Fecha = Dia+"-"+Mes+"-"+Ano;
        jTextFecha.setText(Fecha);
        
           Jbbc.Conectar();
           
              try{
               
                  ResultSet consulta = Jbbc.Estatuto.executeQuery("Select * from Marca");
                  while(consulta.next()){
                      
                       jComboBoxMarca.addItem((consulta.getString("Marca_Articulo")));
                      
                                        }                  
                  
                  Jbbc.Desconectar();
                  
                 }catch(SQLException ex){
              
                    System.out.println("Error al consultar");
                    Jbbc.Desconectar();
              
                                     }        
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelId = new javax.swing.JLabel();
        jLabelDescripcion = new javax.swing.JLabel();
        jLabelPrecio = new javax.swing.JLabel();
        jLabelMarca = new javax.swing.JLabel();
        jLabelModelo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelFechacreacion = new javax.swing.JLabel();
        jComboBoxMarca = new javax.swing.JComboBox();
        jButtonnNuevo = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextIdArticulo = new javax.swing.JTextField();
        jTextFecha = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jTextEditar = new javax.swing.JTextField();
        jButtonEditar = new javax.swing.JButton();
        jTextDescripcion = new javax.swing.JTextField();
        jTextPrecio = new javax.swing.JTextField();
        jTextModelo = new javax.swing.JTextField();
        jTextColor = new javax.swing.JTextField();
        jLabelCantidad = new javax.swing.JLabel();
        jTextCantidad = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Articulos");
        setBackground(java.awt.SystemColor.textHighlight);

        jLabelId.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelId.setText("Id Articulo");

        jLabelDescripcion.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelDescripcion.setText("Descripcion");

        jLabelPrecio.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelPrecio.setText("Precio");

        jLabelMarca.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelMarca.setText("Marca");

        jLabelModelo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelModelo.setText("Modelo");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Color");

        jLabelFechacreacion.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelFechacreacion.setText("Fecha de creacion ");

        jButtonnNuevo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Freddy\\Documents\\NetBeansProjects\\Imagenes y iconos\\document_add.png")); // NOI18N
        jButtonnNuevo.setText("Nuevo");
        jButtonnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnNuevoActionPerformed(evt);
            }
        });

        jButtonGuardar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Freddy\\Documents\\NetBeansProjects\\Imagenes y iconos\\Guardar-documento.png")); // NOI18N
        jButtonGuardar.setText("Guardar ");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonCancelar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Freddy\\Documents\\NetBeansProjects\\Imagenes y iconos\\Cerrar.png")); // NOI18N
        jButtonCancelar.setText("Salir");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Freddy\\Documents\\NetBeansProjects\\Imagenes y iconos\\Articulos.jpg")); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Electrodomesticos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(51, 51, 255))); // NOI18N

        jTextIdArticulo.setEnabled(false);

        jTextFecha.setEnabled(false);
        jTextFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFechaActionPerformed(evt);
            }
        });
        jTextFecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFechaKeyReleased(evt);
            }
        });

        jPanel1.setBackground(java.awt.SystemColor.textHighlight);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Actualizar articulos"));

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEditar)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditar)))
        );

        jLabelCantidad.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelCantidad.setText("Cantidad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(jLabelId)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextIdArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(29, 29, 29)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabelMarca)
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextModelo)
                                                .addComponent(jComboBoxMarca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addGap(25, 25, 25)
                                            .addComponent(jTextColor, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(21, 21, 21)
                                    .addComponent(jLabelModelo))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabelPrecio)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(1, 1, 1))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelCantidad)
                                        .addComponent(jLabelDescripcion))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextCantidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelFechacreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jButtonnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelId)
                            .addComponent(jTextIdArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDescripcion)
                            .addComponent(jTextDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCantidad)
                            .addComponent(jTextCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPrecio)
                            .addComponent(jTextPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMarca)
                            .addComponent(jComboBoxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelModelo)
                            .addComponent(jTextModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jTextColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelFechacreacion)
                            .addComponent(jTextFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
            dispose();
       
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnNuevoActionPerformed

       
       jTextIdArticulo.setText("");
       jTextDescripcion.setText("");
       jTextCantidad.setText("");
       jTextPrecio.setText("");
       jComboBoxMarca.setToolTipText("");
       jTextModelo.setText("");
       jTextColor.setText("");
       jTextFecha.setText("");
       jTextIdArticulo.setText(String.valueOf(Jbbc.Valor_Maximo("IdArticulo", "Articulo")));
       
       FechaActual = new Date(); 
       Integer Dia1 = FechaActual.getDate();
       Integer Mes1 = FechaActual.getMonth()+1;
       Integer Ano1 = FechaActual.getYear()-100;
       String Dia = Dia1.toString();
       String Mes = Mes1.toString();
       String Ano = Ano1.toString();
        
       String Fecha;
        
      // jTextIdArticulo.setText(String.valueOf(Jbbc.Valor_Maximo("IdArticulo", "Articulo")));
      
       if(Dia1<10) Dia = "0"+Dia;
       if(Mes1<10) Mes = "0"+Mes;
       if(Ano1<10) Ano = "0"+Ano;
       Fecha = Dia+"-"+Mes+"-"+Ano;
       jTextFecha.setText(Fecha);
   
    }//GEN-LAST:event_jButtonnNuevoActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed

            boolean Guardar = true;
            Integer IdArticulo = new Integer(jTextIdArticulo.getText());
            String Descripcion = jTextDescripcion.getText();
            Integer Cantidad = new Integer(jTextCantidad.getText());
            Double Precio = new Double(jTextPrecio.getText());
            String Marca = jComboBoxMarca.getSelectedItem().toString();
            String Modelo = jTextModelo.getText();
            String Color = jTextColor.getText();
            String Fecha = Utilidades.EliminarEspacioBlanco(jTextFecha.getText());
            String Dia = Fecha.substring(0, 2);
            String Mes = Fecha.substring(3, 5);
            String Ano = "20"+Fecha.substring(6, 8);
            Fecha = Ano+"-"+Mes+"-"+Dia;
            
          //  if(Utilidades.EliminarEspacioBlanco(jTextId.getText()).equals("") == true)jTextId.setText("0");
            
            if(IdArticulo == 0){
            
              JOptionPane.showMessageDialog(null, "Debe introducir un Id");  
              Guardar = false;
              
                              }
            if(Utilidades.EliminarEspacioBlanco(Descripcion).equals("") == true){
            
              JOptionPane.showMessageDialog(null, "Debe introducir una descripcion");  
              Guardar = false;
                                          
                                          }
            
            if(Cantidad == 0){
            
              JOptionPane.showMessageDialog(null, "Debe introducir una cantidad");  
              Guardar = false;
              
                              }
            
            
            if(Precio == 0){
            
              JOptionPane.showMessageDialog(null, "Debe introducir el precio");  
              Guardar = false;
            
                                            }
            if(Utilidades.EliminarEspacioBlanco(Marca).equals("") == true){
            
              JOptionPane.showMessageDialog(null, "Debe introducir una marca");  
              Guardar = false;
            
                                         }
            if(Utilidades.EliminarEspacioBlanco(Modelo).equals("") == true){
            
              JOptionPane.showMessageDialog(null, "Debe introducir el modelo");  
              Guardar = false;
            
                                           }
            if(Utilidades.EliminarEspacioBlanco(Color).equals("") == true){
            
              JOptionPane.showMessageDialog(null, "Debe introducir el color");  
              Guardar = false;
            
                                            }
           
            
            if(Guardar == true){
            
              Jbbc.Registrar_Articulo(IdArticulo,Descripcion,Cantidad, Precio, Marca, Modelo, Color, Fecha);
              JOptionPane.showMessageDialog(null, "Datos guardados correctamente"); 
            
                               }        
        
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jTextFechaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFechaKeyReleased
       
            
    }//GEN-LAST:event_jTextFechaKeyReleased

    private void jTextFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFechaActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // TODO add your handling code here:
 
           String IdBuscar = Utilidades.EliminarEspacioBlanco(jTextEditar.getText());
           if(IdBuscar.equals("") == true){
           
             JOptionPane.showMessageDialog(null, "Debe digitar un id");    
           
                                          }
           else {
           
              boolean NoEsDigito = false;
              for(int a = 0;a < IdBuscar.length();a++){
              
                 
                 if(Character.isDigit(IdBuscar.charAt(a)) == false){
                 
                    NoEsDigito = true;
                    break;
                     
                                                                   }  
              
                                                      }
              if(NoEsDigito == true){
              
                 JOptionPane.showMessageDialog(null, "Debe digitar un id numerico");  
              
                                    }
              
              else {
              
           Integer IdArticulo = new Integer(jTextEditar.getText());
           Jbbc.Conectar();
           
              try{
               
                  ResultSet consulta = Jbbc.Estatuto.executeQuery("Select * from Articulo where IdArticulo = "+IdArticulo+"");
                  
                  if(consulta.next()){
                  
                    jTextIdArticulo.setText(consulta.getString("IdArticulo").toString());
                    jTextDescripcion.setText(consulta.getString("Descripcion"));
                    jTextCantidad.setText(consulta.getString("Cantidad"));
                    jTextPrecio.setText(consulta.getString("Precio"));
                    jTextModelo.setText(consulta.getString("Modelo"));
                    jTextColor.setText(consulta.getString("Color"));
                    jTextFecha.setText(consulta.getString("FechaDeCreacion"));   
                    
                    
                    // Tabla Marca de articulo combobox
                    
                    String MarcaArticulo = consulta.getString("Marca");
                    Jbbc.Estatuto = Jbbc.Conexion.createStatement(); 
                    
                    ResultSet consulta1 = Jbbc.Estatuto.executeQuery("Select * from Marca");
                    int bucle = 0;
                    while(consulta1.next()){
                      
                         
                        if(MarcaArticulo.equals(consulta1.getString("Marca_Articulo")) == true){
                          
                           jComboBoxMarca.setSelectedIndex(bucle);   
                           break;
                            
                                                                                               }
                        
                        bucle++;
                      
                                        }                    
                    
                 //   
                      
                                      }
                  else{
                  
                    JOptionPane.showMessageDialog(null, "El id no existe");                   
                      
                      }
                  Jbbc.Desconectar();
                  
                 }catch(SQLException ex){
              
                    System.out.println("Error al consultar");
                    Jbbc.Desconectar();
              
                                     }
                  
                   }
           
                }
           
           
        
             
        
    }//GEN-LAST:event_jButtonEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Articulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Articulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Articulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Articulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Articulos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonnNuevo;
    private javax.swing.JComboBox jComboBoxMarca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelFechacreacion;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelModelo;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextCantidad;
    private javax.swing.JTextField jTextColor;
    private javax.swing.JTextField jTextDescripcion;
    private javax.swing.JTextField jTextEditar;
    private javax.swing.JTextField jTextFecha;
    private javax.swing.JTextField jTextIdArticulo;
    private javax.swing.JTextField jTextModelo;
    private javax.swing.JTextField jTextPrecio;
    // End of variables declaration//GEN-END:variables
}
