/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ventas;

/**
 *
 * @author Freddy
 */
public class Menu_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Principal
     */
    public Menu_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuReCliente = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuReArticulo = new javax.swing.JMenuItem();
        jMenuSuplidor = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuConsultar = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuSalirsistema = new javax.swing.JMenuItem();
        jMenuAyuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        setName("Login"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Sistema de ventas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 103, 228, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Electrosoft");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 138, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Freddy\\Documents\\NetBeansProjects\\Imagenes y iconos\\Menu_principal.jpg")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -70, 580, 520));

        jMenuReCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuReCliente.setForeground(new java.awt.Color(0, 51, 51));
        jMenuReCliente.setText("Registrar");

        jMenuItem1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jMenuItem1.setText("Registrar Cliente");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuReCliente.add(jMenuItem1);

        jMenuReArticulo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jMenuReArticulo.setText("Registrar Articulo");
        jMenuReArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuReArticuloActionPerformed(evt);
            }
        });
        jMenuReCliente.add(jMenuReArticulo);

        jMenuSuplidor.setText("Registrar Suplidor");
        jMenuSuplidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSuplidorActionPerformed(evt);
            }
        });
        jMenuReCliente.add(jMenuSuplidor);

        jMenuSalir.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jMenuSalir.setText("Salir");
        jMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalirActionPerformed(evt);
            }
        });
        jMenuReCliente.add(jMenuSalir);

        jMenuBar1.add(jMenuReCliente);

        jMenu3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu3.setForeground(new java.awt.Color(0, 51, 51));
        jMenu3.setText("Consultar");

        jMenuConsultar.setText("Consultar");
        jMenuConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConsultarActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuConsultar);

        jMenuBar1.add(jMenu3);

        jMenu5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu5.setForeground(new java.awt.Color(0, 51, 51));
        jMenu5.setText("Transacciones");
        jMenuBar1.add(jMenu5);

        jMenu1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu1.setForeground(new java.awt.Color(0, 51, 51));
        jMenu1.setText("Reportes");
        jMenuBar1.add(jMenu1);

        jMenu4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenu4.setForeground(new java.awt.Color(0, 51, 51));
        jMenu4.setText("Salir");

        jMenuSalirsistema.setText("Salir del sistema");
        jMenuSalirsistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalirsistemaActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuSalirsistema);

        jMenuBar1.add(jMenu4);

        jMenuAyuda.setText("Ayuda");
        jMenuBar1.add(jMenuAyuda);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Registrar_Clientes();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalirActionPerformed
       Salir();
    }//GEN-LAST:event_jMenuSalirActionPerformed

    private void jMenuReArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuReArticuloActionPerformed
      Registrar_Articulo();
    }//GEN-LAST:event_jMenuReArticuloActionPerformed

    private void jMenuSalirsistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalirsistemaActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuSalirsistemaActionPerformed

    private void jMenuConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConsultarActionPerformed
        Consultar();
    }//GEN-LAST:event_jMenuConsultarActionPerformed

    private void jMenuSuplidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSuplidorActionPerformed
        Suplidor();
    }//GEN-LAST:event_jMenuSuplidorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenuAyuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuConsultar;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuReArticulo;
    private javax.swing.JMenu jMenuReCliente;
    private javax.swing.JMenuItem jMenuSalir;
    private javax.swing.JMenuItem jMenuSalirsistema;
    private javax.swing.JMenuItem jMenuSuplidor;
    // End of variables declaration//GEN-END:variables

    private void Registrar_Clientes() {
     new Registrar_Cliente().setVisible(true);
    }

    private void Registrar_Articulo() {
      new Articulos().setVisible(true);
    }

    private void Salir() {
        System.exit(1);
    }

    private void Consultar() {
     new Consultar().setVisible(true);
    }
    
    private void Suplidor(){
        new Suplidor().setVisible(true);
    }
}
