/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ventas;

//import java.sql.Connection;
//import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.lang.*;
import java.sql.*;

/**
 *
 * @author Freddy
 */
public class Registrar_Cliente extends javax.swing.JFrame {
   // ConexionBD con = new ConexionBD();
  //  Connection cn = con.Conexion();
 
    public Registrar_Cliente() {
        initComponents();
        jTextId.setText(String.valueOf(Jbbc.Valor_Maximo("IdCliente", "Cliente")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jbtnGuardar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jNombre = new javax.swing.JLabel();
        jApellidos = new javax.swing.JLabel();
        jCedula = new javax.swing.JLabel();
        jTelefono = new javax.swing.JLabel();
        jDireccion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jId = new javax.swing.JLabel();
        jTextId = new javax.swing.JFormattedTextField();
        jTextNombres = new javax.swing.JTextField();
        jTextApellidos = new javax.swing.JTextField();
        jTextCedula = new javax.swing.JTextField();
        jTextTeléfono = new javax.swing.JTextField();
        jTextDireccion = new javax.swing.JTextField();
        jTextCiudad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jbtnModificar = new javax.swing.JButton();
        jTextBuscar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Cliente");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Freddy\\Documents\\NetBeansProjects\\Imagenes y iconos\\file_add.png")); // NOI18N
        jButton1.setText("Nuevo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 120, 40));

        jbtnGuardar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Freddy\\Documents\\NetBeansProjects\\Imagenes y iconos\\Guardar-documento.png")); // NOI18N
        jbtnGuardar.setText("Guardar");
        jbtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 130, 40));

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Freddy\\Documents\\NetBeansProjects\\Imagenes y iconos\\Cerrar.png")); // NOI18N
        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 130, 40));

        jPanel1.setBackground(java.awt.SystemColor.textHighlight);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registrar Clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 18), new java.awt.Color(51, 51, 255))); // NOI18N
        jPanel1.setEnabled(false);

        jNombre.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jNombre.setText("Nombres");

        jApellidos.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jApellidos.setText("Apellidos");

        jCedula.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jCedula.setText("Cedula");

        jTelefono.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTelefono.setText("Teléfono");

        jDireccion.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jDireccion.setText("Direccion");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Ciudad");

        jId.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jId.setText("Id");

        jTextId.setEnabled(false);
        jTextId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDireccion, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTelefono, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextDireccion, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextTeléfono, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextCiudad, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(jTextCedula, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jNombre)
                            .addComponent(jId, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextNombres, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(jTextId)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jApellidos)
                            .addComponent(jCedula))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jId, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jNombre)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jTextNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jApellidos)
                    .addComponent(jTextApellidos))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCedula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextCedula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextTeléfono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDireccion)
                    .addComponent(jTextDireccion))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 310));

        jLabel2.setBackground(java.awt.SystemColor.activeCaption);
        jLabel2.setForeground(new java.awt.Color(204, 255, 102));
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Freddy\\Documents\\NetBeansProjects\\Imagenes y iconos\\male_users.png")); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), null));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 120, 300));

        jbtnModificar.setText("Buscar");
        jbtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, -1, -1));

        jTextBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jTextBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 70, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
      //  System.exit(1);
        dispose();
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jbtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGuardarActionPerformed

            boolean Guardar = true;
            Integer IdCliente = new Integer(jTextId.getText());
            String Nombres = jTextNombres.getText();
            String Apellidos = jTextApellidos.getText();
            String Cedula = jTextCedula.getText();
            String Telefono = jTextTeléfono.getText();
            String Direccion = jTextDireccion.getText();
            String Ciudad = jTextCiudad.getText();
            
          //  if(Utilidades.EliminarEspacioBlanco(jTextId.getText()).equals("") == true)jTextId.setText("0");
            
            if(IdCliente == 0){
            
              JOptionPane.showMessageDialog(null, "Debe introducir un Id");  
              Guardar = false;
              
                              }
            if(Utilidades.EliminarEspacioBlanco(Nombres).equals("") == true){
            
              JOptionPane.showMessageDialog(null, "Debe introducir un nombre");  
              Guardar = false;
                                          
                                          }
            if(Utilidades.EliminarEspacioBlanco(Apellidos).equals("") == true){
            
              JOptionPane.showMessageDialog(null, "Debe introducir un apellido");  
              Guardar = false;
            
                                            }
            if(Utilidades.EliminarEspacioBlanco(Cedula).equals("") == true){
            
              JOptionPane.showMessageDialog(null, "Debe introducir un # de cedula");  
              Guardar = false;
            
                                         }
            if(Utilidades.EliminarEspacioBlanco(Telefono).equals("") == true){
            
              JOptionPane.showMessageDialog(null, "Debe introducir un telefono");  
              Guardar = false;
            
                                           }
            if(Utilidades.EliminarEspacioBlanco(Direccion).equals("") == true){
            
              JOptionPane.showMessageDialog(null, "Debe introducir una direccion");  
              Guardar = false;
            
                                            }
            if(Utilidades.EliminarEspacioBlanco(Ciudad).equals("") == true){
            
              JOptionPane.showMessageDialog(null, "Debe introducir una ciudad");  
              Guardar = false;
                
                                         }
            
            
            if(Guardar == true){
            
               Jbbc.Registrar_Cliente(IdCliente, Nombres, Apellidos, Cedula, Telefono, Direccion, Ciudad);
               JOptionPane.showMessageDialog(null, "Datos guardados correctamente"); 
            
                               }
        
  
        
    }//GEN-LAST:event_jbtnGuardarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       jTextId.setText("");
       jTextNombres.setText("");
       jTextApellidos.setText("");
       jTextCedula.setText("");
       jTextTeléfono.setText("");
       jTextDireccion.setText("");
       jTextCiudad.setText("");
       jTextId.setText(String.valueOf(Jbbc.Valor_Maximo("IdCliente", "Cliente")));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnModificarActionPerformed
     //   Modificar_Cliente abrir = new   Modificar_Cliente();
     //   abrir.setVisible(true);
           String IdBuscar = Utilidades.EliminarEspacioBlanco(jTextBuscar.getText());
           if(IdBuscar.equals("") == true){
           
             JOptionPane.showMessageDialog(null, "Debe digitar un id");    
           
                                          }
           else {
           
              boolean NoEsDigito = false;
              for(int a = 0;a < IdBuscar.length();a++){
              
                 
                 if(Character.isDigit(IdBuscar.charAt(a)) == false){
                 
                    NoEsDigito = true;
                    break;
                     
                                                                   }  
              
                                                      }
              if(NoEsDigito == true){
              
                 JOptionPane.showMessageDialog(null, "Debe digitar un id numerico");  
              
                                    }
              
              else {
              
           Integer IdCliente = new Integer(jTextBuscar.getText());
           Jbbc.Conectar();
           
              try{
               
                  ResultSet consulta = Jbbc.Estatuto.executeQuery("Select * from cliente where IdCliente = "+IdCliente+"");
                  
                  if(consulta.next()){
                  
                    jTextId.setText(consulta.getString("IdCliente").toString());
                    jTextNombres.setText(consulta.getString("Nombres"));
                    jTextApellidos.setText(consulta.getString("Apellidos"));
                    jTextCedula.setText(consulta.getString("Cedula"));
                    jTextTeléfono.setText(consulta.getString("Telefono"));
                    jTextDireccion.setText(consulta.getString("Direccion"));
                    jTextCiudad.setText(consulta.getString("Ciudad"));                 
                      
                                      }
                  else{
                  
                    JOptionPane.showMessageDialog(null, "El id no existe");                   
                      
                      }
                  Jbbc.Desconectar();
                  
                 }catch(SQLException ex){
              
                    System.out.println("Error al consultar");
                    Jbbc.Desconectar();
              
                                     }
                  
                   }
           
                }
           
           
        
        
    }//GEN-LAST:event_jbtnModificarActionPerformed

    private void jTextBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextBuscarActionPerformed

    private void jTextIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrar_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrar_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrar_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrar_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrar_Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jApellidos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jCedula;
    private javax.swing.JLabel jDireccion;
    private javax.swing.JLabel jId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jNombre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jTelefono;
    private javax.swing.JTextField jTextApellidos;
    private javax.swing.JTextField jTextBuscar;
    private javax.swing.JTextField jTextCedula;
    private javax.swing.JTextField jTextCiudad;
    private javax.swing.JTextField jTextDireccion;
    private javax.swing.JFormattedTextField jTextId;
    private javax.swing.JTextField jTextNombres;
    private javax.swing.JTextField jTextTeléfono;
    private javax.swing.JButton jbtnGuardar;
    private javax.swing.JButton jbtnModificar;
    // End of variables declaration//GEN-END:variables
}
